"""empty message

Revision ID: 68781a669df1
Revises: aa97ae1c1092
Create Date: 2025-02-04 15:58:12.369996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68781a669df1'
down_revision = 'aa97ae1c1092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=True))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
